### ISSUE TITLE
Automation on Assignees of Issues/PR

### ISSUE THREAD

**Issue by derskythe** [derskythe/docker-github-actions-runner#63]
Need to add workflows/actions for such purpose

**Comment by derskythe** [comment]
### Labeling pull request

- https://github.com/actions/labeler
- Required settings yaml file.

### RegEx Issue Labeler

- https://github.com/marketplace/actions/regex-issue-labeler

### Issue labeler

- https://github.com/github/issue-labeler
- Settings in yaml like in [Labeling pull request]

### Assign

Can't find good one, but find this repo: https://github.com/abinoda/assignee-to-reviewer-action
Latest activity 4 years ago, Node12 but TS.
We can fork or make compilation from different repos to make uber solution all-in-one.

**Comment by derskythe** [comment]
This is all non-boiler code in Assign. 
[index.js](https://github.com/actions-ecosystem/action-add-assignees/blob/main/dist/index.js) file in dist looks like standard lib of GitHub

```TS
import * as github from '@actions/github';
import * as core from '@actions/core';

async function run(): Promise<void> {
  try {
    const githubToken = core.getInput('github_token', { required: true });

    const assignees = core
      .getInput('assignees')
      .split('\n')
      .filter(l => l !== '');
    const [owner, repo] = core.getInput('repo').split('/');
    const number =
      core.getInput('number') === ''
        ? github.context.issue.number
        : parseInt(core.getInput('number'));

    const client = new github.GitHub(githubToken);
    await client.issues.addAssignees({
      assignees,
      owner,
      repo,
      issue_number: number
    });
  } catch (e) {
    core.error(e);
    core.setFailed(e.message);
  }
}

run();
```

action.yml
```YAML
name: Actions Ecosystem Action Add Assignees
description: Add assignees to an issue or a pull request
author: Actions Ecosystem
inputs:
  github_token:
    description: A GitHub token.
    required: true
  assignees:
    description: The assignees' name to be added. Must be separated with line breaks if there're multiple assignees.
    required: true
  repo:
    description: The owner and repository name. e.g.) Codertocat/Hello-World
    required: false
    default: ${{ github.repository }}
  number:
    description: The number of the issue or pull request.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: users
  color: green
```
